[package]
name = "chia-sdk-client"
version = "0.12.0"
edition = "2021"
license = "Apache-2.0"
description = "Utilities for connecting to Chia full node peers via the light wallet protocol."
authors = ["Brandon Haggstrom <me@rigidnetwork.com>"]
homepage = "https://github.com/Rigidity/chia-wallet-sdk"
repository = "https://github.com/Rigidity/chia-wallet-sdk"
readme = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[lints]
workspace = true

[dependencies]
chia-client = { workspace = true }
chia-ssl = { workspace = true }
tokio-tungstenite = { workspace = true }
native-tls = { workspace = true }
thiserror = { workspace = true }
