[package]
name = "chia-sdk-client"
version = "0.8.0"
edition = "2021"

[dependencies]
chia-client.workspace = true
chia-ssl.workspace = true
tokio-tungstenite.workspace = true
native-tls.workspace = true
thiserror.workspace = true
