[package]
name = "chia-sdk-test"
version = "0.8.0"
edition = "2021"

[dependencies]
chia-bls = "0.8.0"
chia-client = "0.8.0"
chia-consensus = "0.8.0"
chia-protocol = "0.8.0"
chia-puzzles = "0.8.0"
chia-traits = "0.8.0"
clvm-utils = "0.8.0"
clvmr = "0.7.0"
futures-channel = "0.3.30"
futures-util = "0.3.30"
indexmap = "2.2.6"
rand = "0.8.5"
rand_chacha = "0.3.1"
sha2 = "0.10.8"
tokio = { version = "1.37.0", features = ["full"] }
native-tls = "0.2.11"
tokio-tungstenite = { version = "0.21.0", features = ["native-tls"] }
anyhow = "1.0.86"
clvm-traits = "0.8.0"
hex-literal = "0.4.1"
once_cell = "1.19.0"
chia-sdk-types = { version = "0.8.0", path = "../chia-sdk-types" }
chia-sdk-signer = { version = "0.8.0", path = "../chia-sdk-signer" }
