[package]
name = "chia-wallet-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
chia-protocol = { git = "https://github.com/rigidity/chia_rs", branch = "develop" }
chia-wallet = { git = "https://github.com/rigidity/chia_rs", branch = "develop" }
chia-bls = { git = "https://github.com/rigidity/chia_rs", branch = "develop" }
chia-client = { git = "https://github.com/rigidity/chia_rs", branch = "develop" }
clvm-traits = { git = "https://github.com/rigidity/chia_rs", branch = "develop" }
clvmr = "0.3.0"
itertools = "0.11.0"
parking_lot = "0.12.1"
tokio = "1.33.0"
log = "0.4.20"
