[package]
name = "chia-wallet-sdk"
version = "0.8.0"
edition = "2021"
license = "Apache-2.0"
description = "An unofficial SDK for building Chia wallets."
authors = ["Brandon Haggstrom <me@rigidnetwork.com>"]
homepage = "https://github.com/Rigidity/chia-wallet-sdk"
repository = "https://github.com/Rigidity/chia-wallet-sdk"

[workspace]
members = ["crates/*"]
resolver = "2"

[dependencies]
tokio = { version = "1.33.0", features = ["macros"] }
sha2 = "0.9.9"
thiserror = "1.0.61"
clvmr = "0.7.0"
chia-protocol = "0.8.0"
chia-bls = "0.8.0"
chia-client = "0.8.0"
clvm-traits = "0.8.0"
clvm-utils = "0.8.0"
chia-ssl = "0.7.0"
chia-traits = "0.8.0"
native-tls = "0.2.11"
tokio-tungstenite = { version = "0.21.0", features = ["native-tls"] }
hex = "0.4.3"
bech32 = "0.9.1"
rand = "0.8.5"
rand_chacha = "0.3.1"
hex-literal = "0.4.1"
indexmap = "2.2.6"

[dev-dependencies]
anyhow = "1.0.82"
bip39 = "2.0.0"
tokio = { version = "1.33.0", features = ["full"] }
