[package]
name = "chia-wallet-sdk"
version = "0.8.0"
edition = "2021"
license = "Apache-2.0"
description = "An unofficial SDK for building Chia wallets."
authors = ["Brandon Haggstrom <me@rigidnetwork.com>"]
homepage = "https://github.com/Rigidity/chia-wallet-sdk"
repository = "https://github.com/Rigidity/chia-wallet-sdk"

[workspace]
members = ["crates/*"]
resolver = "2"

[dependencies]
thiserror = "1.0.61"
chia-protocol = "0.8.0"
hex = "0.4.3"
bech32 = "0.9.1"
rand = "0.8.5"
rand_chacha = "0.3.1"
hex-literal = "0.4.1"
indexmap = "2.2.6"
chia-sdk-client = { version = "0.8.0", path = "./crates/chia-sdk-client" }
chia-sdk-driver = { version = "0.8.0", path = "./crates/chia-sdk-driver" }
chia-sdk-parser = { version = "0.8.0", path = "./crates/chia-sdk-parser" }
chia-sdk-signer = { version = "0.8.0", path = "./crates/chia-sdk-signer" }
chia-sdk-test = { version = "0.8.0", path = "./crates/chia-sdk-test" }
chia-sdk-types = { version = "0.8.0", path = "./crates/chia-sdk-types" }
