[package]
name = "chia-wallet-sdk"
version = "0.7.0"
edition = "2021"
license = "Apache-2.0"
description = "An unofficial SDK for building Chia wallets."
authors = ["Brandon Haggstrom <me@rigidnetwork.com>"]
homepage = "https://github.com/Rigidity/chia-wallet-sdk"
repository = "https://github.com/Rigidity/chia-wallet-sdk"

[features]
sqlite = ["dep:sqlx"]

[dependencies]
tokio = { version = "1.33.0", features = ["macros"] }
indexmap = "2.1.0"
sha2 = "0.9.9"
thiserror = "1.0.50"
clvmr = "0.6.1"
chia-protocol = "0.6.0"
chia-wallet = "0.6.0"
chia-bls = "0.6.0"
chia-client = "0.6.0"
clvm-traits = "0.6.0"
clvm-utils = "0.6.0"
chia-ssl = "0.6.0"
native-tls = "0.2.11"
tokio-tungstenite = { version = "0.21.0", features = ["native-tls"] }
parking_lot = "0.12.1"
hex = "0.4.3"
bech32 = "0.9.1"
rand = "0.8.5"
rand_chacha = "0.3.1"
sqlx = { version = "0.7.4", features = ["runtime-tokio", "sqlite"], optional = true }
hex-literal = "0.4.1"
serde_json = "1.0.115"
serde = { version = "1.0.197", features = ["derive"] }

[dev-dependencies]
bip39 = "2.0.0"
chia-consensus = "0.6.0"
once_cell = "1.19.0"
sqlx = { version = "*", features = ["runtime-tokio", "sqlite"] }
tokio = {version = "*", features = ["full"] }
