[package]
name = "chia-wallet-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.33.0", features = ["macros"] }
log = "0.4.20"
indexmap = "2.1.0"
anyhow = "1.0.75"
sha2 = "0.9.9"
thiserror = "1.0.50"
serde = { version = "1.0.193", features = ["derive"] }
clvmr = "0.4.0"
chia-protocol = "0.4.0"
chia-wallet = "0.4.0"
chia-bls = "0.4.0"
chia-client = "0.4.0"
clvm-traits = "0.3.3"
clvm-utils = "0.4.0"

[dev-dependencies]
bip39 = "2.0.0"
hex = "0.4.3"
hex-literal = "0.4.1"
once_cell = "1.19.0"
