[package]
name = "chia-sdk-types"
version = "0.8.0"
edition = "2021"
license = "Apache-2.0"
description = "Standard Chia types for things such as puzzle info and conditions."
authors = ["Brandon Haggstrom <me@rigidnetwork.com>"]
homepage = "https://github.com/Rigidity/chia-wallet-sdk"
repository = "https://github.com/Rigidity/chia-wallet-sdk"

[dependencies]
chia-bls.workspace = true
chia-protocol.workspace = true
chia-puzzles.workspace = true
clvm-traits.workspace = true

[dev-dependencies]
hex.workspace = true
hex-literal.workspace = true
