[package]
name = "chia-sdk-signer"
version = "0.8.0"
edition = "2021"

[dependencies]
chia-bls.workspace = true
chia-protocol.workspace = true
clvm-traits.workspace = true
clvmr.workspace = true
thiserror.workspace = true
chia-sdk-types.workspace = true

[dev-dependencies]
chia-puzzles.workspace = true
hex.workspace = true
hex-literal.workspace = true
